ORACLE_HOSTNAME=yidigunora
ORACLE_BASE=/opt/oracle
ORACLE_HOME=$ORACLE_BASE/product/19.5/dbhome_1
ORACLE_SID=ORA
NLS_LANG=KOREAN_KOREA.AL32UTF8
if [ -z "$LD_LIBRARY_PATH" ]; then
  LD_LIBRARY_PATH=$ORACLE_HOME/lib
else
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ORACLE_HOME/lib
fi
export ORACLE_HOSTNAME ORACLE_BASE ORACLE_HOME ORACLE_SID NLS_LANG LD_LIBRARY_PATH

PATH=$PATH:$ORACLE_HOME/bin
