GRANT SELECT, INSERT, UPDATE, DELETE ON HR.COUNTRIES TO scott;
GRANT SELECT, INSERT, UPDATE, DELETE ON HR.DEPARTMENTS TO scott;
GRANT SELECT, INSERT, UPDATE, DELETE ON HR.EMPLOYEES TO scott;
GRANT SELECT, INSERT, UPDATE, DELETE ON HR.JOBS TO scott;
GRANT SELECT, INSERT, UPDATE, DELETE ON HR.JOB_HISTORY TO scott;
GRANT SELECT, INSERT, UPDATE, DELETE ON HR.LOCATIONS TO scott;
GRANT SELECT, INSERT, UPDATE, DELETE ON HR.REGIONS TO scott;

GRANT SELECT ON HR.EMP_DETAILS_VIEW TO scott;
GRANT SELECT ON HR.DEPARTMENTS_SEQ TO scott;
GRANT SELECT ON HR.EMPLOYEES_SEQ TO scott;
GRANT SELECT ON HR.LOCATIONS_SEQ TO scott;

GRANT EXECUTE on HR.ADD_JOB_HISTORY TO scott;
GRANT EXECUTE on HR.SECURE_DML TO scott;

CREATE SYNONYM SCOTT.COUNTRIES FOR HR.COUNTRIES;
CREATE SYNONYM SCOTT.DEPARTMENTS FOR HR.DEPARTMENTS;
CREATE SYNONYM SCOTT.EMPLOYEES FOR HR.EMPLOYEES;
CREATE SYNONYM SCOTT.JOBS FOR HR.JOBS;
CREATE SYNONYM SCOTT.JOB_HISTORY FOR HR.JOB_HISTORY;
CREATE SYNONYM SCOTT.LOCATIONS FOR HR.LOCATIONS;
CREATE SYNONYM SCOTT.REGIONS FOR HR.REGIONS;
CREATE SYNONYM SCOTT.EMP_DETAILS_VIEW FOR HR.EMP_DETAILS_VIEW;
CREATE SYNONYM SCOTT.DEPARTMENTS_SEQ FOR HR.DEPARTMENTS_SEQ;
CREATE SYNONYM SCOTT.EMPLOYEES_SEQ FOR HR.EMPLOYEES_SEQ;
CREATE SYNONYM SCOTT.LOCATIONS_SEQ FOR HR.LOCATIONS_SEQ;
CREATE SYNONYM SCOTT.ADD_JOB_HISTORY FOR HR.ADD_JOB_HISTORY;
CREATE SYNONYM SCOTT.SECURE_DML FOR HR.SECURE_DML;
